name: Run tests with Jest

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
